### ISSUE TITLE
don't we need a couple of symlinks for this to work? (at least with Emacs)

### ISSUE THREAD

**Issue by rdiaz02** [EmmanuelCharpentier/patchSynctex#1]
I think we need the following two (assuming our file is called `file`):
`file.Rnw.pdf -> file.Rnw`
`file.Rnw.synctex.gz -> file.synctex.gz`

I am using Emacs. Out of the box, using patchSynctex, I can go from the PDF to the Rnw buffer but I cannot go from the Rnw buffer to the PDF. For instance,  `C-c C-v` (which should fire up my pdf viewer of choice) complains of the file.Rnw.pdf not existing, and using `pdf-sync-forward-search`, from [PDF Tools](https://github.com/politza/pdf-tools/blob/master/lisp/pdf-sync.el), also complains (error is more obscure, though: "epdfinfo: Unable to create synctex scanner, did you run latex with `--synctex=1' ?" and I obviously did).

Now, if I symlink file.Rnw.pdf to point to file.Rnw I can go from the Rnw to the PDF, but going from the PDF to the Rnw now no longer works. But if I also symlink file.Rnw.synctex.gz to file.synctex.gz, I can go from the PDF to the Rnw.

I've seen this using both Okular and PDF Tools, by manually running

```
library(knitr)
library(patchSynctex)
knit2pdf("file.Rnw")
patchSynctex("file", verbose = TRUE)
```

In fact, I faced this exact same problems when using the [jan-glx's patchKnitrSynctex](https://github.com/jan-glx/patchKnitrSynctex) and thus I have a [script that does the linking](http://stackoverflow.com/a/23839749).  The current one that uses patchSynctex is

```
#!/bin/bash
FILE=$1 
BASENAME=$(basename $FILE .Rnw)
RSCRIPT="/home/ramon/bin/Rscript"
$RSCRIPT -e 'library(knitr); library(patchSynctex); opts_knit$set("concordance" = TRUE); knit2pdf("'$1'"); patchSynctex("'$BASENAME'")'
rm $BASENAME.Rnw.synctex.gz
rm $BASENAME.Rnw.pdf
ln -s $BASENAME.synctex.gz $BASENAME.Rnw.synctex.gz
ln -s $BASENAME.pdf $BASENAME.Rnw.pdf
```

Things do not change if I do everything from ESS with the code provided in the documentation (as per page 3 of the current doc in the CRAN package for Emacs 24.4 onwards), and do `M-n r` (to knit) and then `M-n P` to get the PDF. So, in fact, I have no idea how to do this all without calling a shell script<sup>[1](#footnote1)</sup> .

Is this a know issue and the proper way to deal with it? Or am I doing something wrong? If this is the way to deal with it, maybe it could be added to the documentation?

<a name="footnote1">1</a>: We can, however, run the above shell script using the current buffer file name as argument. For instance, we can modify [this gist](https://gist.github.com/tenpn/2367513). I have, in `$HOME/bin/` the above script as `runkKnitr-2.sh` and  in my .emacs, the following:

```
;; Based on https://gist.github.com/tenpn/2367513
(defun run-knit-synctex-on-buffer () 
  (interactive)
  (shell-command (format "runKnitr-2.sh %s" (shell-quote-argument buffer-file-name)))
  )
;; use the keybinding for knit
(define-key ess-noweb-minor-mode-map "\M-nr" 'run-knit-synctex-on-buffer)
```

It works, but my way of "dealing" with this looks like a kludge to me.

**Comment by EmmanuelCharpentier** [comment]
[ Edited ] Works for me. Please see (and test !) the postscriptum file (foo.Rnw). The .pdf file didn't made it through github.

It was obvious for me that this works only if your setup gives you 
normal synchronization between .tex and .pdf files. patchSynctex only 
replaces references to the .tex file with corresponding references to 
the .Rnw file.

Do you think that this should be clarified in the documentation ?

Sincerely,

```
                Emmanuel Charpentier
```

On 30/07/2015 01:17, Ramon Diaz-Uriarte wrote:
[ Edited : original mail edited off ]
[ Edit : foo.Rnw ]
  \documentclass[12pt,a4paper]{article}
  %% This ensures that a synctex file is generated.
  \synctex=1
  \usepackage[utf8]{inputenc}
  \usepackage[T1]{fontenc}
  \author{Emmanuel Charpentier}
  \title{\textsf{patchSynctex} synchronization test}
  \date{August 2015}
  %% This ensures that patchSynctex is present and concordance is active
  <<Libs, echo=FALSE, message=FALSE>>=
  library(patchSynctex)
  opts_knit$set(concordance = TRUE)
  @ 
  \begin{document}
  \maketitle

  Here is an \textsf{R} truism\,: $2+2\,=\,\Sexpr{4}$.

  The forward- and backward-sync both work with emacs.

  This might help when placed in your \texttt{.emacs} file :
  \begin{verbatim}
  (custom-set-variables
   ;; custom-set-variables was added by Custom.
   ;; If you edit it by hand, you could mess it up, so be careful.
   ;; Your init file should contain only one such instance.
   ;; If there is more than one, they won't work right.
   '(TeX-PDF-mode t)
   '(TeX-source-correlate-method (quote synctex))
   '(TeX-source-correlate-mode t)
   '(TeX-source-correlate-start-server t)
   '(show-paren-mode t))
  \end{verbatim}

  Also note at the end of this file the setting of the \verb|TeX-master|\,: This master file \textbf{must} be the \LaTeX{} file, not the \texttt{.Rnw} file. This is done by placing\,:
  \begin{verbatim}
  %%% Local Variables:
  %%% TeX-master: "foo"
  %%% End:
  \end{verbatim}
  at the end of the \texttt{.Rnw file}, \textbf{after} the \verb|\end{document}| macro.
  \end{document}

  %%% Local Variables:
  %%% TeX-master: "foo"
  %%% End:

**Comment by rdiaz02** [comment]
Thanks for your reply but no it doesn't really work for me reliably. Some times it does, some times it doesn't. The whole thing seems extremely brittle: whether (and when) the emacs server is started, and where the point is when I click `C-c C-v` (having it at the end of the first line the first time I do it seems to work best, but not always; having it anywhere else in the file tends to lead to the "whatever.pdf" does not exist). It is inconsistent also since the very same file with different names sometimes works and sometimes does not (yes, I do change the "TeX-master local variable to the right name).  Things seems to be more unreliable if there are several .Rnw files.

It is not something in my .emacs as I have started emacs with a simple .emacs that contains only

```
(custom-set-variables
  '(TeX-PDF-mode t)
  '(TeX-source-correlate-method (quote synctex))
  '(TeX-source-correlate-mode t)
  '(TeX-source-correlate-start-server t)
  '(show-paren-mode t))
```

And yes, I am using your `foo.Rnw` file, and even simpler versions of it. It does not change anything. Even with the `foo.Rnw` in an empty directory with only `foo.Rnw` things sometimes fail.

Ways of making it more likely to work:
- start emacs
- start the emacs server
- load the Rnw
- do C-c C-v at the end of the first line. 
- if the above does not work, close the buffer and open again and move again to the end of the first line.

Ways of making it more unlikely to work:
- not having the server running before you load the Rnw
- using Okular instead of Evince (or pdf-tools)
- typing `C-c C-v` anywhere in the middle of the file:
  - use the example file above, but add several pages with, say, `\clearpage` and some text in each page
  - generate the pdf in the standard way `library(knitr); library(patchSynctex); knit2pdf("file.Rnw");
    patchSynctex("file", verbose = TRUE)`
  - after opening the .Rnw file, do `C-c C-v` in the text of one of these new pages.
- having the .Rnw in a directory with several other Rnw files

Yes, I understand this is not a very helpful report, but I've been trying to figure it out for the last three hours, and I don't see what is really happening (my approach of creating symlinks, though, seems to always work whether with Evince, Okular and Pdf tools, and with pdf tools it does not require the server to be running).

**Comment by EmmanuelCharpentier** [comment]
I could reproduce your problem on an Ubuntu machine ... where I deleted the advice helper from my .emacs (see the patchSynctex-package page in the help).

Did you add the right advice to your .emacs file (emacs <=23.3 and >= 23.4 need different advices) ?

**Comment by rdiaz02** [comment]
Yes, I just tried again now. I am using Emacs 24.5.1 and I copied again the advice you provide for v. 24.4 onwards.  And yes, I have `\synctex=1` on the second line of the `Rnw`.

I can go from the PDF to the Rnw (for instance, using pdf-tools, C-click). But when I try to go from the Rnw to the PDF  it does not work. With `TeX-view` (`C-c C-v`)  I get  `Output file "whatever.Rnw.pdf" does not exist.` and with `pdf-sync-forward-search` (`C-c C-g`) , a function in pdf-tools, I get `epdfinfo: Error opening /home/ramon/blablabla/whatever.Rnw.pdf:No such file or directory` (if I have `TeX-master: "whatever"` as a local variable) or `epdfinfo: Unable to create synctex scanner, did you run latex with '--synctex=1' ?` if I don't. (I do not need this local variable when using my simple minded approach with links).

And I have tried with both texi2pdf and pdflatex. Things do not change.

Now, for the sake of being practical: maybe this is a problem in my end (no one else, except you and I, have chimed in this issue) or maybe this problem shows up sometimes. But maybe it is not worth spending too much time now given the unconfirmed status of the problem (and that the simple link thing solves the issue).

**Comment by EmmanuelCharpentier** [comment]
One year later, I have made no progress on this issue. My reproduction on an Ubuntu machine mysteriously vanished.

Do you still have this problem ?, or should I consider it a fluke ?

**Comment by rdiaz02** [comment]
I am not able to reproduce it right now (though it seems to occasionally happen). However, maybe given the quasi-poltergeist status of this not-easily-reproducible thing, it is not really worth it to try to chase it. I can close if you want.
