### ISSUE TITLE
Patching synctex misses input or includes

### ISSUE THREAD

**Issue by harmsk** [EmmanuelCharpentier/patchSynctex#3]
patchSynctex() does not patch Rnw files included with \input{} or \include{} in the main Rnw file.

Working example: [knitr-with-input.tar.gz](https://github.com/EmmanuelCharpentier/patchSynctex/files/522298/knitr-with-input.tar.gz)

``` sh
make rRestore
make
```

**Comment by EmmanuelCharpentier** [comment]
1) `patchSynctex` doesn't patch the `.Rnw` files ; it patches the corresponding `.synctex[.gz]` files...

2) Indeed, this will have trouble with included parts (the "right way" to do this is to use children chunks, see [the docs](http://yihui.name/knitr/demo/child/)). 

But Yihui Xie has decided not to support concordance with these children chunks. See [his comments](https://github.com/yihui/knitr/issues/225) in the issues of his github repository. There is little one can do without forking `knitr`. And I won't do it (this would require much more of my time...).

Given the current complexity of `knitr`, its wide non-`\LaTeX` targe audience (`mardown` seems dominant these days) and the narrowness of this potential feature, I can understand Yihui Xie's decision...

So, unless you have new ideas about this old thorn in my flank, I close this issue.
